/-
Copyright (c) 2026 Zichen Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zichen Wang
-/
module

public import ReasLib.FunctionalAnalysis.SequenceSpace.RationalTimeOperator.Parametrization.LorentzCoordinates
public import ReasLib.MeasureTheory.UnitL2.IntervalCoordinateOperator

/-!
# Unit-difference Lorentz detectors
-/

public section

namespace Lorentz

/-- The dual unit difference `e_i^* - e_j^*`. -/
noncomputable def unitDifference (i j : ℕ) : L1Seq :=
  lp.single 1 i (1 : ℝ) - lp.single 1 j (1 : ℝ)

/-- The Lorentz point generated by a unit difference, with zero source
parameter. -/
noncomputable def unitDifferenceDetector (d : C0Seq) (i j : ℕ) : parametrizedSubspace d :=
  parametrizedPoint d (unitDifference i j) 0

/-- If the parametrizing vector annihilates the two selected coordinates, the
unit-difference detector has zero positive coordinate. -/
theorem positiveCoordinate_unitDifferenceDetector
    (d : C0Seq) (hd : d ≠ 0) (i j : ℕ)
    (hpair : C0Seq.pairingL d (unitDifference i j) = 0) :
    positiveCoordinate d hd (unitDifferenceDetector d i j) = 0 := by
  unfold unitDifferenceDetector
  rw [positiveCoordinate_apply]
  simp [hpair]

/-- The negative coordinate of a unit-difference detector is its exact
interval-coordinate difference together with the scalar pairing. -/
theorem negativeCoordinate_unitDifferenceDetector
    (d : C0Seq) (hd : d ≠ 0) (i j : ℕ) :
    negativeCoordinate d hd (unitDifferenceDetector d i j) =
      HilbertProd2.mk (L1Seq.intervalCoordinateOperator (unitDifference i j))
        (-C0Seq.pairingL d (unitDifference i j) / 2) := by
  unfold unitDifferenceDetector
  rw [negativeCoordinate_apply]
  congr 1
  ring

/-- The interval-coordinate component of a unit difference is the difference
of the two rational interval vectors. -/
theorem intervalCoordinate_unitDifference (i j : ℕ) :
    L1Seq.intervalCoordinateOperator (unitDifference i j) =
      UnitL2.rationalIntervalVec i - UnitL2.rationalIntervalVec j := by
  unfold unitDifference
  rw [map_sub, L1Seq.intervalCoordinateOperator_apply_single,
    L1Seq.intervalCoordinateOperator_apply_single]

end Lorentz
