/-
Copyright (c) 2026 Zichen Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zichen Wang
-/
module

public import ReasLib.FunctionalAnalysis.SequenceSpace.RationalTimeOperator.Parametrization.LorentzCoordinates
public import ReasLib.FunctionalAnalysis.SequenceSpace.RationalTimeOperator.Parametrization.Pairing
public import ReasLib.FunctionalAnalysis.SequenceSpace.RationalTimeOperator.Parametrization.LorentzEnergy
public import ReasLib.Topology.RationalTime
public import ReasLib.FunctionalAnalysis.SequenceSpace.C0.StrictMono
public import ReasLib.MeasureTheory.UnitL2.IntervalCoordinateOperator

/-!
# Unit-difference Lorentz detectors
-/

public section

open Topology
open scoped InnerProductSpace

namespace Lorentz

/-- The dual unit difference `e_i^* - e_j^*`. -/
noncomputable def unitDifference (i j : ℕ) : L1Seq :=
  lp.single 1 i (1 : ℝ) - lp.single 1 j (1 : ℝ)

/-- The absolute mass of a difference of two unit coordinates is at most two. -/
theorem norm_unitDifference_le_two (i j : ℕ) : ‖unitDifference i j‖ ≤ 2 := by
  have hone : 0 < (1 : ENNReal) := by norm_num
  have hi : ‖(lp.single 1 i (1 : ℝ) : L1Seq)‖ = 1 := by
    simpa only [norm_one] using
      lp.norm_single (E := fun _ : ℕ ↦ ℝ) hone i (1 : ℝ)
  have hj : ‖(lp.single 1 j (1 : ℝ) : L1Seq)‖ = 1 := by
    simpa only [norm_one] using
      lp.norm_single (E := fun _ : ℕ ↦ ℝ) hone j (1 : ℝ)
  have h := norm_sub_le (lp.single 1 i (1 : ℝ) : L1Seq) (lp.single 1 j (1 : ℝ))
  rw [hi, hj] at h
  simpa only [unitDifference, one_add_one_eq_two] using h

/-- The Lorentz point generated by a unit difference, with zero source
parameter. -/
noncomputable def unitDifferenceDetector (d : C0Seq) (i j : ℕ) : parametrizedSubspace d :=
  parametrizedPoint d (unitDifference i j) 0

/-- If the parametrizing vector annihilates the two selected coordinates, the
unit-difference detector has zero positive coordinate. -/
theorem positiveCoordinate_unitDifferenceDetector
    (d : C0Seq) (hd : d ≠ 0) (i j : ℕ)
    (hpair : C0Seq.pairingL d (unitDifference i j) = 0) :
    positiveCoordinate d hd (unitDifferenceDetector d i j) = 0 := by
  unfold unitDifferenceDetector
  rw [positiveCoordinate_apply]
  simp [hpair]

/-- The negative coordinate of a unit-difference detector is its exact
interval-coordinate difference together with the scalar pairing. -/
theorem negativeCoordinate_unitDifferenceDetector
    (d : C0Seq) (hd : d ≠ 0) (i j : ℕ) :
    negativeCoordinate d hd (unitDifferenceDetector d i j) =
      HilbertProd2.mk (L1Seq.intervalCoordinateOperator (unitDifference i j))
        (-C0Seq.pairingL d (unitDifference i j) / 2) := by
  unfold unitDifferenceDetector
  rw [negativeCoordinate_apply]
  congr 1
  ring

/-- The interval-coordinate component of a unit difference is the difference
of the two rational interval vectors. -/
theorem intervalCoordinate_unitDifference (i j : ℕ) :
    L1Seq.intervalCoordinateOperator (unitDifference i j) =
      UnitL2.rationalIntervalVec i - UnitL2.rationalIntervalVec j := by
  unfold unitDifference
  rw [map_sub, L1Seq.intervalCoordinateOperator_apply_single,
    L1Seq.intervalCoordinateOperator_apply_single]

/-- The unit-difference detector has the expected rational-time distance. -/
theorem norm_intervalCoordinate_unitDifference (i j : ℕ) :
    ‖L1Seq.intervalCoordinateOperator (unitDifference i j)‖ =
      Real.sqrt |rationalTime i - rationalTime j| := by
  rw [intervalCoordinate_unitDifference]
  simpa only [UnitL2.rationalIntervalVec] using
    (UnitL2.norm_sub_intervalVec
      (⟨rationalTime i, (rationalTime_mem_Ioo i).1.le,
        (rationalTime_mem_Ioo i).2.le⟩ : unitInterval)
      (⟨rationalTime j, (rationalTime_mem_Ioo j).1.le,
        (rationalTime_mem_Ioo j).2.le⟩ : unitInterval))

/-- A strictly increasing rational-time subsequence approaching the `i`th time
produces unit-difference detectors whose interval coordinates vanish. -/
theorem tendsto_norm_intervalCoordinate_unitDifference
    (i : ℕ) {φ : ℕ → ℕ}
    (hφ : Filter.Tendsto (rationalTime ∘ φ) Filter.atTop
      (𝓝 (rationalTime i))) :
    Filter.Tendsto
      (fun n ↦ ‖L1Seq.intervalCoordinateOperator
        (unitDifference i (φ n))‖)
      Filter.atTop (𝓝 0) := by
  have hdiff : Filter.Tendsto
      (fun n ↦ |rationalTime i - rationalTime (φ n)|)
      Filter.atTop (𝓝 0) := by
    have hsub : Filter.Tendsto
        (fun n ↦ rationalTime i - rationalTime (φ n))
        Filter.atTop (𝓝 0) := by
      have hconst : Filter.Tendsto (fun _ : ℕ ↦ rationalTime i)
          Filter.atTop (𝓝 (rationalTime i)) := tendsto_const_nhds
      simpa only [Function.comp_apply, sub_self] using
        (hconst.sub hφ)
    simpa only [abs_zero] using hsub.abs
  have hsqrt := Real.continuous_sqrt.continuousAt.tendsto.comp hdiff
  simpa only [norm_intervalCoordinate_unitDifference, Real.sqrt_zero,
    Function.comp_def] using hsqrt

/-- Pairing with a unit difference reads the corresponding coordinate
difference. -/
theorem pairingL_unitDifference (x : C0Seq) (i j : ℕ) :
    C0Seq.pairingL x (unitDifference i j) = x i - x j := by
  unfold unitDifference
  rw [map_sub]
  have hsingle (n : ℕ) :
      C0Seq.pairingL x (lp.single 1 n (1 : ℝ)) = x n := by
    rw [C0Seq.pairingL_apply, tsum_eq_single n]
    · simp
    · intro m hm
      simp [lp.single_apply, hm]
  rw [hsingle, hsingle]

/-- Along a strictly increasing detector-index subsequence, the residual
pairing with a unit difference converges to the selected residual coordinate. -/
theorem tendsto_pairingL_unitDifference_strictMono
    (x : C0Seq) (i : ℕ) {φ : ℕ → ℕ} (hφ : StrictMono φ) :
    Filter.Tendsto
      (fun n ↦ C0Seq.pairingL x (unitDifference i (φ n)))
      Filter.atTop (𝓝 (x i)) := by
  have hz := C0Seq.tendsto_apply_strictMono x hφ
  have hc : Filter.Tendsto (fun _ : ℕ ↦ x i) Filter.atTop (𝓝 (x i)) :=
    tendsto_const_nhds
  simpa only [pairingL_unitDifference, sub_zero] using (hc.sub hz)

/-- The interval-coordinate inner product with a fixed dual sequence vanishes
along a rational-time detector subsequence. -/
theorem tendsto_inner_unitDifference_strictMono
    (u : L1Seq) (i : ℕ) {φ : ℕ → ℕ}
    (hφ : Filter.Tendsto (rationalTime ∘ φ) Filter.atTop
      (𝓝 (rationalTime i))) :
    Filter.Tendsto
      (fun n ↦ ⟪L1Seq.intervalCoordinateOperator u,
        L1Seq.intervalCoordinateOperator (unitDifference i (φ n))⟫_ℝ)
      Filter.atTop (𝓝 0) := by
  have hn := tendsto_norm_intervalCoordinate_unitDifference i hφ
  have hv : Filter.Tendsto
      (fun n ↦ L1Seq.intervalCoordinateOperator (unitDifference i (φ n)))
      Filter.atTop (𝓝 (0 : UnitL2)) :=
    tendsto_zero_iff_norm_tendsto_zero.mpr hn
  have hu : Filter.Tendsto (fun _ : ℕ ↦ L1Seq.intervalCoordinateOperator u)
      Filter.atTop (𝓝 (L1Seq.intervalCoordinateOperator u)) := tendsto_const_nhds
  have hi : Filter.Tendsto
      (fun n ↦ ⟪L1Seq.intervalCoordinateOperator u,
        L1Seq.intervalCoordinateOperator (unitDifference i (φ n))⟫_ℝ)
      Filter.atTop
      (𝓝 ⟪L1Seq.intervalCoordinateOperator u, (0 : UnitL2)⟫_ℝ) :=
    hu.inner hv
  simpa using hi

/-- The full symmetric pairing with unit-difference detectors converges to the
selected residual coordinate when the parametrizing vector annihilates the
detector coordinates. -/
private theorem symmetricForm_unitDifferenceDetector_aux
    (d x : C0Seq) (u : L1Seq) (i j : ℕ)
    (hpair : C0Seq.pairingL d (unitDifference i j) = 0) :
    C0Seq.symmetricForm (x, u) (unitDifferenceDetector d i j) =
      C0Seq.pairingL (x + L1Seq.positiveOperator u) (unitDifference i j) -
        2 * ⟪L1Seq.intervalCoordinateOperator u,
          L1Seq.intervalCoordinateOperator (unitDifference i j)⟫_ℝ := by
  unfold unitDifferenceDetector
  rw [parametrizedPoint_apply]
  simpa [hpair] using (detectorPairingFormula d x u (unitDifference i j))

theorem tendsto_symmetricForm_unitDifferenceDetector
    (d x : C0Seq) (u : L1Seq) (i : ℕ) {φ : ℕ → ℕ}
    (hφ : StrictMono φ)
    (hpair : ∀ n, C0Seq.pairingL d (unitDifference i (φ n)) = 0)
    (hφtime : Filter.Tendsto (rationalTime ∘ φ) Filter.atTop
      (𝓝 (rationalTime i))) :
    Filter.Tendsto
      (fun n ↦ C0Seq.symmetricForm (x, u)
        (unitDifferenceDetector d i (φ n)))
      Filter.atTop
      (𝓝 ((x + L1Seq.positiveOperator u) i)) := by
  have hfirst := tendsto_pairingL_unitDifference_strictMono
    (x + L1Seq.positiveOperator u) i hφ
  have hinner := tendsto_inner_unitDifference_strictMono u i hφtime
  have hform : ∀ n,
      C0Seq.symmetricForm (x, u) (unitDifferenceDetector d i (φ n)) =
        C0Seq.pairingL (x + L1Seq.positiveOperator u)
            (unitDifference i (φ n)) -
          2 * ⟪L1Seq.intervalCoordinateOperator u,
            L1Seq.intervalCoordinateOperator (unitDifference i (φ n))⟫_ℝ := by
    intro n
    simpa only [hpair n, mul_zero, sub_zero] using
      symmetricForm_unitDifferenceDetector_aux d x u i (φ n) (hpair n)
  have hscaled := hinner.const_mul 2
  have hsub := hfirst.sub hscaled
  have hsub' : Filter.Tendsto
      (fun n ↦ C0Seq.pairingL (x + L1Seq.positiveOperator u)
          (unitDifference i (φ n)) -
        2 * ⟪L1Seq.intervalCoordinateOperator u,
          L1Seq.intervalCoordinateOperator (unitDifference i (φ n))⟫_ℝ)
      Filter.atTop (𝓝 ((x + L1Seq.positiveOperator u) i - 2 * 0)) := by
    simpa only [Function.comp_apply] using hsub
  have hh := hsub'.congr'
    (Filter.Eventually.of_forall (fun n ↦ (hform n).symm))
  simpa only [sub_zero, mul_zero] using hh

/-- Under the annihilation condition, the detector norm is exactly the
interval-coordinate difference norm. -/
theorem norm_negativeCoordinate_unitDifferenceDetector
    (d : C0Seq) (hd : d ≠ 0) (i j : ℕ)
    (hpair : C0Seq.pairingL d (unitDifference i j) = 0) :
    ‖negativeCoordinate d hd (unitDifferenceDetector d i j)‖ =
      ‖L1Seq.intervalCoordinateOperator (unitDifference i j)‖ := by
  rw [negativeCoordinate_unitDifferenceDetector]
  have hsq := HilbertProd2.norm_mk_sq
    (L1Seq.intervalCoordinateOperator (unitDifference i j))
    (-(C0Seq.pairingL d (unitDifference i j)) / 2)
  have hsq' :
      ‖HilbertProd2.mk (L1Seq.intervalCoordinateOperator (unitDifference i j))
          (-(C0Seq.pairingL d (unitDifference i j)) / 2)‖ ^ 2 =
        ‖L1Seq.intervalCoordinateOperator (unitDifference i j)‖ ^ 2 := by
    simpa [hpair] using hsq
  apply (sq_eq_sq₀ (norm_nonneg _) (norm_nonneg _)).mp
  exact hsq'

/-- Under the annihilation condition, the finite detector has nonpositive
quadratic energy equal to the negative squared interval distance. -/
theorem quadraticPairing_unitDifferenceDetector
    (d : C0Seq) (hd : d ≠ 0) (i j : ℕ)
    (hpair : C0Seq.pairingL d (unitDifference i j) = 0) :
    C0Seq.quadraticPairing (unitDifferenceDetector d i j) =
      -‖L1Seq.intervalCoordinateOperator (unitDifference i j)‖ ^ 2 := by
  rw [quadraticIdentity d hd]
  rw [positiveCoordinate_unitDifferenceDetector d hd i j hpair]
  rw [norm_negativeCoordinate_unitDifferenceDetector d hd i j hpair]
  norm_num

/-- The symmetric pairing with a unit-difference detector is given by the
detector pairing formula, with no remote-copy approximation involved. -/
theorem symmetricForm_unitDifferenceDetector
    (d x : C0Seq) (u : L1Seq) (i j : ℕ)
    (hpair : C0Seq.pairingL d (unitDifference i j) = 0) :
    C0Seq.symmetricForm (x, u) (unitDifferenceDetector d i j) =
      C0Seq.pairingL (x + L1Seq.positiveOperator u) (unitDifference i j) -
        2 * ⟪L1Seq.intervalCoordinateOperator u,
          L1Seq.intervalCoordinateOperator (unitDifference i j)⟫_ℝ -
        C0Seq.pairingL d u * C0Seq.pairingL d (unitDifference i j) := by
  unfold unitDifferenceDetector
  rw [parametrizedPoint_apply]
  simpa [hpair] using (detectorPairingFormula d x u (unitDifference i j))

/-- The diagonal coordinate of the triangular operator on a forward unit
difference records the jump in its interval kernel. -/
theorem positiveOperator_unitDifference_apply_left (i j : ℕ) (hij : i < j) :
    L1Seq.positiveOperator (unitDifference i j) i =
      rationalTime i - 2 * min (rationalTime i) (rationalTime j) := by
  have hne : i ≠ j := ne_of_lt hij
  have hji : j ≠ i := Ne.symm hne
  have hdiag : unitDifference i j i = 1 := by
    simp [unitDifference, lp.single_apply, hne]
  have htail : (∑' m : ℕ, if i < m then min (rationalTime i) (rationalTime m) *
      unitDifference i j m else 0) = -min (rationalTime i) (rationalTime j) := by
    rw [tsum_eq_single j]
    · simp [hij, unitDifference, lp.single_apply, hji]
    · intro m hm
      by_cases hmi : m = i
      · subst m
        simp
      · simp [unitDifference, lp.single_apply, hm, hmi]
  rw [L1Seq.positiveOperator_apply, hdiag, htail]
  ring

/-- Close forward interval endpoints force a sizeable negative diagonal
coordinate of the operator on their unit difference. -/
theorem positiveOperator_unitDifference_apply_left_lt (i j : ℕ) (hij : i < j)
    (hclose : |rationalTime i - rationalTime j| < rationalTime i / 4) :
    L1Seq.positiveOperator (unitDifference i j) i < -rationalTime i / 2 := by
  rw [positiveOperator_unitDifference_apply_left i j hij]
  have ht := (rationalTime_mem_Ioo i).1
  have hdiff := (abs_lt.mp hclose).2
  have hm : 3 * rationalTime i / 4 < min (rationalTime i) (rationalTime j) := by
    apply lt_min
    · linarith
    · linarith
  linarith

/-- The primal component of a close forward unit detector has a positive
lower norm bound, even though its Hilbert component can be arbitrarily small. -/
theorem unitDifferenceDetector_primal_norm_lower (d : C0Seq) (i j : ℕ) (hij : i < j)
    (hclose : |rationalTime i - rationalTime j| < rationalTime i / 4) :
    rationalTime i / 2 < ‖(unitDifferenceDetector d i j : C0Seq × L1Seq).1‖ := by
  have hc := positiveOperator_unitDifference_apply_left_lt i j hij hclose
  have hn := C0Seq.abs_apply_le_norm (L1Seq.positiveOperator (unitDifference i j)) i
  have ha := neg_le_abs (L1Seq.positiveOperator (unitDifference i j) i)
  unfold unitDifferenceDetector
  rw [parametrizedPoint_apply, parametrization_apply]
  simp only [zero_smul, add_zero, norm_neg]
  linarith

end Lorentz
